version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "web"
      - "dependencies"
    reviewers:
      - "darrenvong"
      - "lucaslcode"

