import { HostingStatus, MeetupStatus, ParkingDetails, SleepingArrangement, SmokingLocation } from "features/profile/constants";

export interface User {
    id: number,
    latitude: number,
    longitude: number,
    radius: number,
    username: string,
    city: string,
    hometown: string,
    createdAt: string,
    name: string,
    gender: string,
    pronouns: string,
    age: number,
    fullName: string,
    hostingStatus: HostingStatus,
    meetupStatus: MeetupStatus,
    communityStanding: number,
    occupation: string,
    education: string,
    aboutMe: string,
    myTravels: string,
    thingsILike: string,
    aboutPlace: string,
    additionalInformation: string,
    maxGuests: number,
    lastMinute: boolean,
    hasPets: boolean,
    acceptsPets: boolean,
    petDetails: string,
    hasKids: boolean,
    acceptsKids: boolean,
    kidDetails: string,
    hasHousemates: boolean,
    housemateDetails: string,
    wheelchairAccessible: boolean,
    smokingAllowed: SmokingLocation,
    smokesAtHome: boolean,
    drinkingAllowed: boolean,
    drinksAtHome: boolean,
    otherHostInfo: string,
    sleepingArrangement: SleepingArrangement,
    sleepingDetails: string,
    area: string,
    houseRules: string,
    parking: boolean,
    parkingDetails: ParkingDetails,
    campingOk: boolean,
    timezoneArea: string,
    languageAbilities: {string: string},
    regionsVisited: string[],
    regionsLived: string[],
    numberOfReferences: number,
    numberOfFriends: number,
    avatar: string,
    avatarThumbnail: string
  };

  interface LanguageAbility {
    "id": number,
    "name": string,
    "fluency": string,
    "user": number,
    "language": number
}