---
# This is our "staging" specific values for the web-frontend "deployment".  The values here will override any values set
# in the upstream helm chart, and will override any values in values.yaml but only for staging (next, on commits/merges to master) deploys.
deployment:
  ingress:
    hosts:
      - host: staging.couchers.dev
        paths:
          - /

  # This is to "redirect" users from the old "next" URL into the new one
  ingress_secondary:
    enabled: true
    name: app-frontend-staging-redirect
    hosts:
      - host: next.couchershq.org
        paths:
          - /
    annotations:
      nginx.ingress.kubernetes.io/permanent-redirect: https://staging.couchers.dev

envFile: .env.staging
