---
# This is our "production" specific values for the web-frontend "deployment".  The values here will override any values set
# in the upstream helm chart, and will override any values in values.yaml but only for production (live, customer-facing) deploys.
deployment:

  ingress:
    hosts:
      - host: preprod.couchers.org
        paths:
          - /

  # We need more resources on production/live than our defaults from values.yaml
  resources:
    limits:
     cpu: 500m
     memory: 800Mi
    requests:
     cpu: 100m
     memory: 800Mi

  # These are for env-specific environment variables, but we can set in the global (values.yaml) file if we want, and override optionally inside values-env.yaml
  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=720" # Testing at 90% of maximum of 800Mi above

envFile: .env.production
