---
# This is our "dev" specific values for the web-frontend "deployment".  The values here will override any values set
# in the upstream helm chart, and will override any values in values.yaml but only for development deploys.
deployment:

  # Using a custom hostname on dev
  ingress:
    hosts:
      # We use "dynamic dev environments" based on the branch name we populate the global "namespace" value and inject it here
      - host: '{{ (include "namespace" .) }}.couchers.dev'
        paths:
          - /

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=160" # This should be 80% of maximum of 200M below

  resources:
    limits:
     cpu: 500m
     memory: 300Mi
    requests:
     cpu: 50m
     memory: 300Mi

# Using an custom .env file injected into the running container.  See: templates/env.yaml
envFile: .env.development
