---
# Production-specific environment variables / overrides in here
deployment:

  ingress:
    hosts:
      - host: couchers.org
        paths:
          - /
      - host: prod.couchers.org
        paths:
          - /

  autoscaling:
    enabled: true

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max-old-space-size=200" # Testing at 50% of maximum of 2000M below
    - name: NODE_DEBUG
      value: "http,fs,cluster,child_process,module"

  resources:
    limits:
     cpu: 1
     memory: 400Mi
    requests:
     cpu: 500m
     memory: 400Mi

envFile: .env.production
