/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterPageAssociation
 */
export interface ClusterPageAssociation {
    /**
     * 
     * @type {number}
     * @memberof ClusterPageAssociation
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterPageAssociation
     */
    readonly page: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterPageAssociation
     */
    readonly cluster: number;
}

export function ClusterPageAssociationFromJSON(json: any): ClusterPageAssociation {
    return ClusterPageAssociationFromJSONTyped(json, false);
}

export function ClusterPageAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterPageAssociation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'page': json['page'],
        'cluster': json['cluster'],
    };
}

export function ClusterPageAssociationToJSON(value?: ClusterPageAssociation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

