/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleEnum,
    RoleEnumFromJSON,
    RoleEnumFromJSONTyped,
    RoleEnumToJSON,
} from './RoleEnum';

/**
 * 
 * @export
 * @interface ClusterSubscription
 */
export interface ClusterSubscription {
    /**
     * 
     * @type {number}
     * @memberof ClusterSubscription
     */
    readonly id: number;
    /**
     * 
     * @type {RoleEnum}
     * @memberof ClusterSubscription
     */
    role: RoleEnum;
    /**
     * 
     * @type {number}
     * @memberof ClusterSubscription
     */
    readonly user: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterSubscription
     */
    cluster: number;
}

export function ClusterSubscriptionFromJSON(json: any): ClusterSubscription {
    return ClusterSubscriptionFromJSONTyped(json, false);
}

export function ClusterSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': RoleEnumFromJSON(json['role']),
        'user': json['user'],
        'cluster': json['cluster'],
    };
}

export function ClusterSubscriptionToJSON(value?: ClusterSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': RoleEnumToJSON(value.role),
        'cluster': value.cluster,
    };
}

