/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ContributeEnum,
    ContributeEnumFromJSON,
    ContributeEnumFromJSONTyped,
    ContributeEnumToJSON,
} from './ContributeEnum';
import {
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';

/**
 * @type ContributorFormContribute
 * 
 * @export
 */
export type ContributorFormContribute = ContributeEnum | NullEnum;

export function ContributorFormContributeFromJSON(json: any): ContributorFormContribute {
    return ContributorFormContributeFromJSONTyped(json, false);
}

export function ContributorFormContributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContributorFormContribute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ContributeEnumFromJSONTyped(json, true), ...NullEnumFromJSONTyped(json, true) };
}

export function ContributorFormContributeToJSON(value?: ContributorFormContribute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...ContributeEnumToJSON(value), ...NullEnumToJSON(value) };
}

