/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DeliveryTypeEnum = {
    Push: 'push',
    Email: 'email',
    Digest: 'digest'
} as const;
export type DeliveryTypeEnum = typeof DeliveryTypeEnum[keyof typeof DeliveryTypeEnum];


export function DeliveryTypeEnumFromJSON(json: any): DeliveryTypeEnum {
    return DeliveryTypeEnumFromJSONTyped(json, false);
}

export function DeliveryTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryTypeEnum {
    return json as DeliveryTypeEnum;
}

export function DeliveryTypeEnumToJSON(value?: DeliveryTypeEnum | null): any {
    return value as any;
}

