/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventOccurrenceAttendeeStatusEnum = {
    Going: 'going',
    Maybe: 'maybe'
} as const;
export type EventOccurrenceAttendeeStatusEnum = typeof EventOccurrenceAttendeeStatusEnum[keyof typeof EventOccurrenceAttendeeStatusEnum];


export function EventOccurrenceAttendeeStatusEnumFromJSON(json: any): EventOccurrenceAttendeeStatusEnum {
    return EventOccurrenceAttendeeStatusEnumFromJSONTyped(json, false);
}

export function EventOccurrenceAttendeeStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventOccurrenceAttendeeStatusEnum {
    return json as EventOccurrenceAttendeeStatusEnum;
}

export function EventOccurrenceAttendeeStatusEnumToJSON(value?: EventOccurrenceAttendeeStatusEnum | null): any {
    return value as any;
}

