/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventOccurrenceAttendeeStatusEnum,
    EventOccurrenceAttendeeStatusEnumFromJSON,
    EventOccurrenceAttendeeStatusEnumFromJSONTyped,
    EventOccurrenceAttendeeStatusEnumToJSON,
} from './EventOccurrenceAttendeeStatusEnum';

/**
 * 
 * @export
 * @interface EventOccurrenceAttendee
 */
export interface EventOccurrenceAttendee {
    /**
     * 
     * @type {number}
     * @memberof EventOccurrenceAttendee
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof EventOccurrenceAttendee
     */
    readonly user: number;
    /**
     * 
     * @type {number}
     * @memberof EventOccurrenceAttendee
     */
    readonly occurrence: number;
    /**
     * 
     * @type {Date}
     * @memberof EventOccurrenceAttendee
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {EventOccurrenceAttendeeStatusEnum}
     * @memberof EventOccurrenceAttendee
     */
    status: EventOccurrenceAttendeeStatusEnum;
}

export function EventOccurrenceAttendeeFromJSON(json: any): EventOccurrenceAttendee {
    return EventOccurrenceAttendeeFromJSONTyped(json, false);
}

export function EventOccurrenceAttendeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventOccurrenceAttendee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'occurrence': json['occurrence'],
        'createdAt': (new Date(json['created_at'])),
        'status': EventOccurrenceAttendeeStatusEnumFromJSON(json['status']),
    };
}

export function EventOccurrenceAttendeeToJSON(value?: EventOccurrenceAttendee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': EventOccurrenceAttendeeStatusEnumToJSON(value.status),
    };
}

