/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FriendRelationshipStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Rejected: 'rejected',
    Cancelled: 'cancelled'
} as const;
export type FriendRelationshipStatusEnum = typeof FriendRelationshipStatusEnum[keyof typeof FriendRelationshipStatusEnum];


export function FriendRelationshipStatusEnumFromJSON(json: any): FriendRelationshipStatusEnum {
    return FriendRelationshipStatusEnumFromJSONTyped(json, false);
}

export function FriendRelationshipStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendRelationshipStatusEnum {
    return json as FriendRelationshipStatusEnum;
}

export function FriendRelationshipStatusEnumToJSON(value?: FriendRelationshipStatusEnum | null): any {
    return value as any;
}

