/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HostRequestStatusTargetEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Rejected: 'rejected',
    Confirmed: 'confirmed',
    Cancelled: 'cancelled'
} as const;
export type HostRequestStatusTargetEnum = typeof HostRequestStatusTargetEnum[keyof typeof HostRequestStatusTargetEnum];


export function HostRequestStatusTargetEnumFromJSON(json: any): HostRequestStatusTargetEnum {
    return HostRequestStatusTargetEnumFromJSONTyped(json, false);
}

export function HostRequestStatusTargetEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostRequestStatusTargetEnum {
    return json as HostRequestStatusTargetEnum;
}

export function HostRequestStatusTargetEnumToJSON(value?: HostRequestStatusTargetEnum | null): any {
    return value as any;
}

