/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Status34bEnum,
    Status34bEnumFromJSON,
    Status34bEnumFromJSONTyped,
    Status34bEnumToJSON,
} from './Status34bEnum';

/**
 * 
 * @export
 * @interface HostRequest
 */
export interface HostRequest {
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof HostRequest
     */
    startAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof HostRequest
     */
    endAt: Date;
    /**
     * 
     * @type {Status34bEnum}
     * @memberof HostRequest
     */
    status?: Status34bEnum;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    userLastSeenMessageId?: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    hostLastSeenMessageId?: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    userSentReferenceReminders?: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    hostSentReferenceReminders?: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    readonly conversation: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    readonly user: number;
    /**
     * 
     * @type {number}
     * @memberof HostRequest
     */
    readonly hostUser: number;
}

export function HostRequestFromJSON(json: any): HostRequest {
    return HostRequestFromJSONTyped(json, false);
}

export function HostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startAt': (new Date(json['start_at'])),
        'endAt': (new Date(json['end_at'])),
        'status': !exists(json, 'status') ? undefined : Status34bEnumFromJSON(json['status']),
        'userLastSeenMessageId': !exists(json, 'user_last_seen_message_id') ? undefined : json['user_last_seen_message_id'],
        'hostLastSeenMessageId': !exists(json, 'host_last_seen_message_id') ? undefined : json['host_last_seen_message_id'],
        'userSentReferenceReminders': !exists(json, 'user_sent_reference_reminders') ? undefined : json['user_sent_reference_reminders'],
        'hostSentReferenceReminders': !exists(json, 'host_sent_reference_reminders') ? undefined : json['host_sent_reference_reminders'],
        'conversation': json['conversation'],
        'user': json['user'],
        'hostUser': json['host_user'],
    };
}

export function HostRequestToJSON(value?: HostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_at': (value.startAt.toISOString()),
        'end_at': (value.endAt.toISOString()),
        'status': Status34bEnumToJSON(value.status),
        'user_last_seen_message_id': value.userLastSeenMessageId,
        'host_last_seen_message_id': value.hostLastSeenMessageId,
        'user_sent_reference_reminders': value.userSentReferenceReminders,
        'host_sent_reference_reminders': value.hostSentReferenceReminders,
    };
}

