/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitiatedUpload
 */
export interface InitiatedUpload {
    /**
     * 
     * @type {string}
     * @memberof InitiatedUpload
     */
    readonly key: string;
    /**
     * 
     * @type {Date}
     * @memberof InitiatedUpload
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InitiatedUpload
     */
    readonly expiresAt: Date;
    /**
     * 
     * @type {number}
     * @memberof InitiatedUpload
     */
    readonly user: number;
}

export function InitiatedUploadFromJSON(json: any): InitiatedUpload {
    return InitiatedUploadFromJSONTyped(json, false);
}

export function InitiatedUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitiatedUpload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'createdAt': (new Date(json['created_at'])),
        'expiresAt': (new Date(json['expires_at'])),
        'user': json['user'],
    };
}

export function InitiatedUploadToJSON(value?: InitiatedUpload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

