/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MeetupStatusEnum = {
    WantsToMeetup: 'wants_to_meetup',
    OpenToMeetup: 'open_to_meetup',
    DoesNotWantToMeetup: 'does_not_want_to_meetup'
} as const;
export type MeetupStatusEnum = typeof MeetupStatusEnum[keyof typeof MeetupStatusEnum];


export function MeetupStatusEnumFromJSON(json: any): MeetupStatusEnum {
    return MeetupStatusEnumFromJSONTyped(json, false);
}

export function MeetupStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetupStatusEnum {
    return json as MeetupStatusEnum;
}

export function MeetupStatusEnumToJSON(value?: MeetupStatusEnum | null): any {
    return value as any;
}

