/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MessageTypeEnum,
    MessageTypeEnumFromJSON,
    MessageTypeEnumFromJSONTyped,
    MessageTypeEnumToJSON,
} from './MessageTypeEnum';
import {
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';

/**
 * @type MessageMessageType
 * 
 * @export
 */
export type MessageMessageType = MessageTypeEnum | NullEnum;

export function MessageMessageTypeFromJSON(json: any): MessageMessageType {
    return MessageMessageTypeFromJSONTyped(json, false);
}

export function MessageMessageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageMessageType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...MessageTypeEnumFromJSONTyped(json, true), ...NullEnumFromJSONTyped(json, true) };
}

export function MessageMessageTypeToJSON(value?: MessageMessageType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...MessageTypeEnumToJSON(value), ...NullEnumToJSON(value) };
}

