/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MessageTypeEnum = {
    Text: 'text',
    ChatCreated: 'chat_created',
    ChatEdited: 'chat_edited',
    UserInvited: 'user_invited',
    UserLeft: 'user_left',
    UserMadeAdmin: 'user_made_admin',
    UserRemovedAdmin: 'user_removed_admin',
    HostRequestStatusChnage: 'host_request_status_chnage',
    UserRemoved: 'user_removed'
} as const;
export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];


export function MessageTypeEnumFromJSON(json: any): MessageTypeEnum {
    return MessageTypeEnumFromJSONTyped(json, false);
}

export function MessageTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageTypeEnum {
    return json as MessageTypeEnum;
}

export function MessageTypeEnumToJSON(value?: MessageTypeEnum | null): any {
    return value as any;
}

