/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PageTypeEnum = {
    MainPage: 'main_page',
    Place: 'place',
    Guide: 'guide'
} as const;
export type PageTypeEnum = typeof PageTypeEnum[keyof typeof PageTypeEnum];


export function PageTypeEnumFromJSON(json: any): PageTypeEnum {
    return PageTypeEnumFromJSONTyped(json, false);
}

export function PageTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageTypeEnum {
    return json as PageTypeEnum;
}

export function PageTypeEnumToJSON(value?: PageTypeEnum | null): any {
    return value as any;
}

