/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventOccurrence,
    EventOccurrenceFromJSON,
    EventOccurrenceFromJSONTyped,
    EventOccurrenceToJSON,
} from './EventOccurrence';

/**
 * 
 * @export
 * @interface PaginatedEventOccurrenceList
 */
export interface PaginatedEventOccurrenceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEventOccurrenceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventOccurrenceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventOccurrenceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<EventOccurrence>}
     * @memberof PaginatedEventOccurrenceList
     */
    results?: Array<EventOccurrence>;
}

export function PaginatedEventOccurrenceListFromJSON(json: any): PaginatedEventOccurrenceList {
    return PaginatedEventOccurrenceListFromJSONTyped(json, false);
}

export function PaginatedEventOccurrenceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEventOccurrenceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(EventOccurrenceFromJSON)),
    };
}

export function PaginatedEventOccurrenceListToJSON(value?: PaginatedEventOccurrenceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(EventOccurrenceToJSON)),
    };
}

