/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Comment,
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface PaginatedCommentList
 */
export interface PaginatedCommentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCommentList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCommentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCommentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Comment>}
     * @memberof PaginatedCommentList
     */
    results?: Array<Comment>;
}

export function PaginatedCommentListFromJSON(json: any): PaginatedCommentList {
    return PaginatedCommentListFromJSONTyped(json, false);
}

export function PaginatedCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCommentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CommentFromJSON)),
    };
}

export function PaginatedCommentListToJSON(value?: PaginatedCommentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CommentToJSON)),
    };
}

