/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegionVisited,
    RegionVisitedFromJSON,
    RegionVisitedFromJSONTyped,
    RegionVisitedToJSON,
} from './RegionVisited';

/**
 * 
 * @export
 * @interface PaginatedRegionVisitedList
 */
export interface PaginatedRegionVisitedList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRegionVisitedList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionVisitedList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionVisitedList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RegionVisited>}
     * @memberof PaginatedRegionVisitedList
     */
    results?: Array<RegionVisited>;
}

export function PaginatedRegionVisitedListFromJSON(json: any): PaginatedRegionVisitedList {
    return PaginatedRegionVisitedListFromJSONTyped(json, false);
}

export function PaginatedRegionVisitedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRegionVisitedList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(RegionVisitedFromJSON)),
    };
}

export function PaginatedRegionVisitedListToJSON(value?: PaginatedRegionVisitedList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(RegionVisitedToJSON)),
    };
}

