/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventSubscription,
    EventSubscriptionFromJSON,
    EventSubscriptionFromJSONTyped,
    EventSubscriptionToJSON,
} from './EventSubscription';

/**
 * 
 * @export
 * @interface PaginatedEventSubscriptionList
 */
export interface PaginatedEventSubscriptionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEventSubscriptionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventSubscriptionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventSubscriptionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<EventSubscription>}
     * @memberof PaginatedEventSubscriptionList
     */
    results?: Array<EventSubscription>;
}

export function PaginatedEventSubscriptionListFromJSON(json: any): PaginatedEventSubscriptionList {
    return PaginatedEventSubscriptionListFromJSONTyped(json, false);
}

export function PaginatedEventSubscriptionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEventSubscriptionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(EventSubscriptionFromJSON)),
    };
}

export function PaginatedEventSubscriptionListToJSON(value?: PaginatedEventSubscriptionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(EventSubscriptionToJSON)),
    };
}

