/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Event,
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
} from './Event';

/**
 * 
 * @export
 * @interface PaginatedEventList
 */
export interface PaginatedEventList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEventList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEventList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Event>}
     * @memberof PaginatedEventList
     */
    results?: Array<Event>;
}

export function PaginatedEventListFromJSON(json: any): PaginatedEventList {
    return PaginatedEventListFromJSONTyped(json, false);
}

export function PaginatedEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEventList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(EventFromJSON)),
    };
}

export function PaginatedEventListToJSON(value?: PaginatedEventList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(EventToJSON)),
    };
}

