/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscussionSubscription,
    DiscussionSubscriptionFromJSON,
    DiscussionSubscriptionFromJSONTyped,
    DiscussionSubscriptionToJSON,
} from './DiscussionSubscription';

/**
 * 
 * @export
 * @interface PaginatedDiscussionSubscriptionList
 */
export interface PaginatedDiscussionSubscriptionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDiscussionSubscriptionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDiscussionSubscriptionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDiscussionSubscriptionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<DiscussionSubscription>}
     * @memberof PaginatedDiscussionSubscriptionList
     */
    results?: Array<DiscussionSubscription>;
}

export function PaginatedDiscussionSubscriptionListFromJSON(json: any): PaginatedDiscussionSubscriptionList {
    return PaginatedDiscussionSubscriptionListFromJSONTyped(json, false);
}

export function PaginatedDiscussionSubscriptionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDiscussionSubscriptionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DiscussionSubscriptionFromJSON)),
    };
}

export function PaginatedDiscussionSubscriptionListToJSON(value?: PaginatedDiscussionSubscriptionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DiscussionSubscriptionToJSON)),
    };
}

