/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Thread,
    ThreadFromJSON,
    ThreadFromJSONTyped,
    ThreadToJSON,
} from './Thread';

/**
 * 
 * @export
 * @interface PaginatedThreadList
 */
export interface PaginatedThreadList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedThreadList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedThreadList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedThreadList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Thread>}
     * @memberof PaginatedThreadList
     */
    results?: Array<Thread>;
}

export function PaginatedThreadListFromJSON(json: any): PaginatedThreadList {
    return PaginatedThreadListFromJSONTyped(json, false);
}

export function PaginatedThreadListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedThreadList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ThreadFromJSON)),
    };
}

export function PaginatedThreadListToJSON(value?: PaginatedThreadList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ThreadToJSON)),
    };
}

