/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reply,
    ReplyFromJSON,
    ReplyFromJSONTyped,
    ReplyToJSON,
} from './Reply';

/**
 * 
 * @export
 * @interface PaginatedReplyList
 */
export interface PaginatedReplyList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedReplyList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReplyList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReplyList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Reply>}
     * @memberof PaginatedReplyList
     */
    results?: Array<Reply>;
}

export function PaginatedReplyListFromJSON(json: any): PaginatedReplyList {
    return PaginatedReplyListFromJSONTyped(json, false);
}

export function PaginatedReplyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReplyList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ReplyFromJSON)),
    };
}

export function PaginatedReplyListToJSON(value?: PaginatedReplyList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ReplyToJSON)),
    };
}

