/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Discussion,
    DiscussionFromJSON,
    DiscussionFromJSONTyped,
    DiscussionToJSON,
} from './Discussion';

/**
 * 
 * @export
 * @interface PaginatedDiscussionList
 */
export interface PaginatedDiscussionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDiscussionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDiscussionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDiscussionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Discussion>}
     * @memberof PaginatedDiscussionList
     */
    results?: Array<Discussion>;
}

export function PaginatedDiscussionListFromJSON(json: any): PaginatedDiscussionList {
    return PaginatedDiscussionListFromJSONTyped(json, false);
}

export function PaginatedDiscussionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDiscussionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DiscussionFromJSON)),
    };
}

export function PaginatedDiscussionListToJSON(value?: PaginatedDiscussionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DiscussionToJSON)),
    };
}

