/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Page,
    PageFromJSON,
    PageFromJSONTyped,
    PageToJSON,
} from './Page';

/**
 * 
 * @export
 * @interface PaginatedPageList
 */
export interface PaginatedPageList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPageList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPageList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPageList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Page>}
     * @memberof PaginatedPageList
     */
    results?: Array<Page>;
}

export function PaginatedPageListFromJSON(json: any): PaginatedPageList {
    return PaginatedPageListFromJSONTyped(json, false);
}

export function PaginatedPageListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPageList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(PageFromJSON)),
    };
}

export function PaginatedPageListToJSON(value?: PaginatedPageList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(PageToJSON)),
    };
}

