/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Email,
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface PaginatedEmailList
 */
export interface PaginatedEmailList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEmailList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEmailList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEmailList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Email>}
     * @memberof PaginatedEmailList
     */
    results?: Array<Email>;
}

export function PaginatedEmailListFromJSON(json: any): PaginatedEmailList {
    return PaginatedEmailListFromJSONTyped(json, false);
}

export function PaginatedEmailListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEmailList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(EmailFromJSON)),
    };
}

export function PaginatedEmailListToJSON(value?: PaginatedEmailList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(EmailToJSON)),
    };
}

