/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Region,
    RegionFromJSON,
    RegionFromJSONTyped,
    RegionToJSON,
} from './Region';

/**
 * 
 * @export
 * @interface PaginatedRegionList
 */
export interface PaginatedRegionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRegionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Region>}
     * @memberof PaginatedRegionList
     */
    results?: Array<Region>;
}

export function PaginatedRegionListFromJSON(json: any): PaginatedRegionList {
    return PaginatedRegionListFromJSONTyped(json, false);
}

export function PaginatedRegionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRegionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(RegionFromJSON)),
    };
}

export function PaginatedRegionListToJSON(value?: PaginatedRegionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(RegionToJSON)),
    };
}

