/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegionLived,
    RegionLivedFromJSON,
    RegionLivedFromJSONTyped,
    RegionLivedToJSON,
} from './RegionLived';

/**
 * 
 * @export
 * @interface PaginatedRegionLivedList
 */
export interface PaginatedRegionLivedList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRegionLivedList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionLivedList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRegionLivedList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RegionLived>}
     * @memberof PaginatedRegionLivedList
     */
    results?: Array<RegionLived>;
}

export function PaginatedRegionLivedListFromJSON(json: any): PaginatedRegionLivedList {
    return PaginatedRegionLivedListFromJSONTyped(json, false);
}

export function PaginatedRegionLivedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRegionLivedList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(RegionLivedFromJSON)),
    };
}

export function PaginatedRegionLivedListToJSON(value?: PaginatedRegionLivedList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(RegionLivedToJSON)),
    };
}

