/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClusterEventAssociation,
    ClusterEventAssociationFromJSON,
    ClusterEventAssociationFromJSONTyped,
    ClusterEventAssociationToJSON,
} from './ClusterEventAssociation';

/**
 * 
 * @export
 * @interface PaginatedClusterEventAssociationList
 */
export interface PaginatedClusterEventAssociationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedClusterEventAssociationList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClusterEventAssociationList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClusterEventAssociationList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ClusterEventAssociation>}
     * @memberof PaginatedClusterEventAssociationList
     */
    results?: Array<ClusterEventAssociation>;
}

export function PaginatedClusterEventAssociationListFromJSON(json: any): PaginatedClusterEventAssociationList {
    return PaginatedClusterEventAssociationListFromJSONTyped(json, false);
}

export function PaginatedClusterEventAssociationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedClusterEventAssociationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ClusterEventAssociationFromJSON)),
    };
}

export function PaginatedClusterEventAssociationListToJSON(value?: PaginatedClusterEventAssociationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ClusterEventAssociationToJSON)),
    };
}

