/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetail,
    UserDetailFromJSON,
    UserDetailFromJSONTyped,
    UserDetailToJSON,
} from './UserDetail';

/**
 * 
 * @export
 * @interface PaginatedUserDetailList
 */
export interface PaginatedUserDetailList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedUserDetailList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUserDetailList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUserDetailList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<UserDetail>}
     * @memberof PaginatedUserDetailList
     */
    results?: Array<UserDetail>;
}

export function PaginatedUserDetailListFromJSON(json: any): PaginatedUserDetailList {
    return PaginatedUserDetailListFromJSONTyped(json, false);
}

export function PaginatedUserDetailListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUserDetailList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(UserDetailFromJSON)),
    };
}

export function PaginatedUserDetailListToJSON(value?: PaginatedUserDetailList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(UserDetailToJSON)),
    };
}

