/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Node,
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 * 
 * @export
 * @interface PaginatedNodeList
 */
export interface PaginatedNodeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedNodeList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedNodeList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedNodeList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Node>}
     * @memberof PaginatedNodeList
     */
    results?: Array<Node>;
}

export function PaginatedNodeListFromJSON(json: any): PaginatedNodeList {
    return PaginatedNodeListFromJSONTyped(json, false);
}

export function PaginatedNodeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedNodeList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(NodeFromJSON)),
    };
}

export function PaginatedNodeListToJSON(value?: PaginatedNodeList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(NodeToJSON)),
    };
}

