/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LanguageAbility,
    LanguageAbilityFromJSON,
    LanguageAbilityFromJSONTyped,
    LanguageAbilityToJSON,
} from './LanguageAbility';

/**
 * 
 * @export
 * @interface PaginatedLanguageAbilityList
 */
export interface PaginatedLanguageAbilityList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLanguageAbilityList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLanguageAbilityList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLanguageAbilityList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LanguageAbility>}
     * @memberof PaginatedLanguageAbilityList
     */
    results?: Array<LanguageAbility>;
}

export function PaginatedLanguageAbilityListFromJSON(json: any): PaginatedLanguageAbilityList {
    return PaginatedLanguageAbilityListFromJSONTyped(json, false);
}

export function PaginatedLanguageAbilityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLanguageAbilityList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LanguageAbilityFromJSON)),
    };
}

export function PaginatedLanguageAbilityListToJSON(value?: PaginatedLanguageAbilityList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LanguageAbilityToJSON)),
    };
}

