/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OneTimeDonation,
    OneTimeDonationFromJSON,
    OneTimeDonationFromJSONTyped,
    OneTimeDonationToJSON,
} from './OneTimeDonation';

/**
 * 
 * @export
 * @interface PaginatedOneTimeDonationList
 */
export interface PaginatedOneTimeDonationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedOneTimeDonationList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOneTimeDonationList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOneTimeDonationList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<OneTimeDonation>}
     * @memberof PaginatedOneTimeDonationList
     */
    results?: Array<OneTimeDonation>;
}

export function PaginatedOneTimeDonationListFromJSON(json: any): PaginatedOneTimeDonationList {
    return PaginatedOneTimeDonationListFromJSONTyped(json, false);
}

export function PaginatedOneTimeDonationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedOneTimeDonationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(OneTimeDonationFromJSON)),
    };
}

export function PaginatedOneTimeDonationListToJSON(value?: PaginatedOneTimeDonationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(OneTimeDonationToJSON)),
    };
}

