/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Conversation,
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
} from './Conversation';

/**
 * 
 * @export
 * @interface PaginatedConversationList
 */
export interface PaginatedConversationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedConversationList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedConversationList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedConversationList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Conversation>}
     * @memberof PaginatedConversationList
     */
    results?: Array<Conversation>;
}

export function PaginatedConversationListFromJSON(json: any): PaginatedConversationList {
    return PaginatedConversationListFromJSONTyped(json, false);
}

export function PaginatedConversationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedConversationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ConversationFromJSON)),
    };
}

export function PaginatedConversationListToJSON(value?: PaginatedConversationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ConversationToJSON)),
    };
}

