/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InitiatedUpload,
    InitiatedUploadFromJSON,
    InitiatedUploadFromJSONTyped,
    InitiatedUploadToJSON,
} from './InitiatedUpload';

/**
 * 
 * @export
 * @interface PaginatedInitiatedUploadList
 */
export interface PaginatedInitiatedUploadList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedInitiatedUploadList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInitiatedUploadList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInitiatedUploadList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<InitiatedUpload>}
     * @memberof PaginatedInitiatedUploadList
     */
    results?: Array<InitiatedUpload>;
}

export function PaginatedInitiatedUploadListFromJSON(json: any): PaginatedInitiatedUploadList {
    return PaginatedInitiatedUploadListFromJSONTyped(json, false);
}

export function PaginatedInitiatedUploadListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedInitiatedUploadList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(InitiatedUploadFromJSON)),
    };
}

export function PaginatedInitiatedUploadListToJSON(value?: PaginatedInitiatedUploadList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(InitiatedUploadToJSON)),
    };
}

