/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reference,
    ReferenceFromJSON,
    ReferenceFromJSONTyped,
    ReferenceToJSON,
} from './Reference';

/**
 * 
 * @export
 * @interface PaginatedReferenceList
 */
export interface PaginatedReferenceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedReferenceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReferenceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReferenceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Reference>}
     * @memberof PaginatedReferenceList
     */
    results?: Array<Reference>;
}

export function PaginatedReferenceListFromJSON(json: any): PaginatedReferenceList {
    return PaginatedReferenceListFromJSONTyped(json, false);
}

export function PaginatedReferenceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReferenceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ReferenceFromJSON)),
    };
}

export function PaginatedReferenceListToJSON(value?: PaginatedReferenceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ReferenceToJSON)),
    };
}

