/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import {
    SmokingAllowedEnum,
    SmokingAllowedEnumFromJSON,
    SmokingAllowedEnumFromJSONTyped,
    SmokingAllowedEnumToJSON,
} from './SmokingAllowedEnum';

/**
 * @type PatchedUserDetailSmokingAllowed
 * 
 * @export
 */
export type PatchedUserDetailSmokingAllowed = NullEnum | SmokingAllowedEnum;

export function PatchedUserDetailSmokingAllowedFromJSON(json: any): PatchedUserDetailSmokingAllowed {
    return PatchedUserDetailSmokingAllowedFromJSONTyped(json, false);
}

export function PatchedUserDetailSmokingAllowedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetailSmokingAllowed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...NullEnumFromJSONTyped(json, true), ...SmokingAllowedEnumFromJSONTyped(json, true) };
}

export function PatchedUserDetailSmokingAllowedToJSON(value?: PatchedUserDetailSmokingAllowed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...NullEnumToJSON(value), ...SmokingAllowedEnumToJSON(value) };
}

