/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedClusterDiscussionAssociation
 */
export interface PatchedClusterDiscussionAssociation {
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterDiscussionAssociation
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterDiscussionAssociation
     */
    readonly discussion?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterDiscussionAssociation
     */
    readonly cluster?: number;
}

export function PatchedClusterDiscussionAssociationFromJSON(json: any): PatchedClusterDiscussionAssociation {
    return PatchedClusterDiscussionAssociationFromJSONTyped(json, false);
}

export function PatchedClusterDiscussionAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedClusterDiscussionAssociation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'discussion': !exists(json, 'discussion') ? undefined : json['discussion'],
        'cluster': !exists(json, 'cluster') ? undefined : json['cluster'],
    };
}

export function PatchedClusterDiscussionAssociationToJSON(value?: PatchedClusterDiscussionAssociation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

