/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedEmail
 */
export interface PatchedEmail {
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmail
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly senderName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly senderEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly recipient?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly subject?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly plain?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmail
     */
    readonly html?: string;
}

export function PatchedEmailFromJSON(json: any): PatchedEmail {
    return PatchedEmailFromJSONTyped(json, false);
}

export function PatchedEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'senderName': !exists(json, 'sender_name') ? undefined : json['sender_name'],
        'senderEmail': !exists(json, 'sender_email') ? undefined : json['sender_email'],
        'recipient': !exists(json, 'recipient') ? undefined : json['recipient'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'plain': !exists(json, 'plain') ? undefined : json['plain'],
        'html': !exists(json, 'html') ? undefined : json['html'],
    };
}

export function PatchedEmailToJSON(value?: PatchedEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

