/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCluster
 */
export interface PatchedCluster {
    /**
     * 
     * @type {number}
     * @memberof PatchedCluster
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedCluster
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCluster
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCluster
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedCluster
     */
    officialCluster?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedCluster
     */
    readonly parentNode?: number;
}

export function PatchedClusterFromJSON(json: any): PatchedCluster {
    return PatchedClusterFromJSONTyped(json, false);
}

export function PatchedClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCluster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'officialCluster': !exists(json, 'official_cluster') ? undefined : json['official_cluster'],
        'parentNode': !exists(json, 'parent_node') ? undefined : json['parent_node'],
    };
}

export function PatchedClusterToJSON(value?: PatchedCluster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'official_cluster': value.officialCluster,
    };
}

