/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HostingStatusEnum,
    HostingStatusEnumFromJSON,
    HostingStatusEnumFromJSONTyped,
    HostingStatusEnumToJSON,
} from './HostingStatusEnum';
import {
    MeetupStatusEnum,
    MeetupStatusEnumFromJSON,
    MeetupStatusEnumFromJSONTyped,
    MeetupStatusEnumToJSON,
} from './MeetupStatusEnum';
import {
    PatchedUserDetailParkingDetails,
    PatchedUserDetailParkingDetailsFromJSON,
    PatchedUserDetailParkingDetailsFromJSONTyped,
    PatchedUserDetailParkingDetailsToJSON,
} from './PatchedUserDetailParkingDetails';
import {
    PatchedUserDetailSleepingArrangement,
    PatchedUserDetailSleepingArrangementFromJSON,
    PatchedUserDetailSleepingArrangementFromJSONTyped,
    PatchedUserDetailSleepingArrangementToJSON,
} from './PatchedUserDetailSleepingArrangement';
import {
    PatchedUserDetailSmokingAllowed,
    PatchedUserDetailSmokingAllowedFromJSON,
    PatchedUserDetailSmokingAllowedFromJSONTyped,
    PatchedUserDetailSmokingAllowedToJSON,
} from './PatchedUserDetailSmokingAllowed';

/**
 * 
 * @export
 * @interface PatchedUserDetail
 */
export interface PatchedUserDetail {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    username?: string | null;
    /**
     * Required
     * @type {string}
     * @memberof PatchedUserDetail
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    geom?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    geomRadius?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    hometown?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUserDetail
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUserDetail
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    lastNotifiedMessageId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    lastNotifiedRequestMessageId?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    pronouns?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUserDetail
     */
    birthdate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    fullName?: string | null;
    /**
     * 
     * @type {HostingStatusEnum}
     * @memberof PatchedUserDetail
     */
    hostingStatus?: HostingStatusEnum;
    /**
     * 
     * @type {MeetupStatusEnum}
     * @memberof PatchedUserDetail
     */
    meetupStatus?: MeetupStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    communityStanding?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    education?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    aboutMe?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    myTravels?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    thingsILike?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    aboutPlace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    additionalInformation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    maxGuests?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    lastMinute?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    hasPets?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    acceptsPets?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    petDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    hasKids?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    acceptsKids?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    kidDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    hasHousemates?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    housemateDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    wheelchairAccessible?: boolean | null;
    /**
     * 
     * @type {PatchedUserDetailSmokingAllowed}
     * @memberof PatchedUserDetail
     */
    smokingAllowed?: PatchedUserDetailSmokingAllowed | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    smokesAtHome?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    drinkingAllowed?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    drinksAtHome?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    otherHostInfo?: string | null;
    /**
     * 
     * @type {PatchedUserDetailSleepingArrangement}
     * @memberof PatchedUserDetail
     */
    sleepingArrangement?: PatchedUserDetailSleepingArrangement | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    sleepingDetails?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    area?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    houseRules?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    parking?: boolean | null;
    /**
     * 
     * @type {PatchedUserDetailParkingDetails}
     * @memberof PatchedUserDetail
     */
    parkingDetails?: PatchedUserDetailParkingDetails | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    campingOk?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    acceptedTos?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    acceptedCommunityGuidelines?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    filledContributorForm?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    onboardingEmailsSent?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUserDetail
     */
    readonly lastOnboardingEmailSentAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    addedToMailingList?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUserDetail
     */
    lastDigestSentAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    readonly stripeCustomerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    readonly stripeCustomerIdOld?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserDetail
     */
    newNotificationsEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    readonly avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetail
     */
    readonly timezoneArea?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    readonly age?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PatchedUserDetail
     */
    readonly languageAbilities?: { [key: string]: any; };
    /**
     * 
     * @type {Array<any>}
     * @memberof PatchedUserDetail
     */
    readonly regionsVisited?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof PatchedUserDetail
     */
    readonly regionsLived?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    readonly numberOfReferences?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetail
     */
    readonly numberOfFriends?: number;
}

export function PatchedUserDetailFromJSON(json: any): PatchedUserDetail {
    return PatchedUserDetailFromJSONTyped(json, false);
}

export function PatchedUserDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'geom': !exists(json, 'geom') ? undefined : json['geom'],
        'geomRadius': !exists(json, 'geom_radius') ? undefined : json['geom_radius'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'hometown': !exists(json, 'hometown') ? undefined : json['hometown'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'lastNotifiedMessageId': !exists(json, 'last_notified_message_id') ? undefined : json['last_notified_message_id'],
        'lastNotifiedRequestMessageId': !exists(json, 'last_notified_request_message_id') ? undefined : json['last_notified_request_message_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'pronouns': !exists(json, 'pronouns') ? undefined : json['pronouns'],
        'birthdate': !exists(json, 'birthdate') ? undefined : (json['birthdate'] === null ? null : new Date(json['birthdate'])),
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'hostingStatus': !exists(json, 'hosting_status') ? undefined : HostingStatusEnumFromJSON(json['hosting_status']),
        'meetupStatus': !exists(json, 'meetup_status') ? undefined : MeetupStatusEnumFromJSON(json['meetup_status']),
        'communityStanding': !exists(json, 'community_standing') ? undefined : json['community_standing'],
        'occupation': !exists(json, 'occupation') ? undefined : json['occupation'],
        'education': !exists(json, 'education') ? undefined : json['education'],
        'aboutMe': !exists(json, 'about_me') ? undefined : json['about_me'],
        'myTravels': !exists(json, 'my_travels') ? undefined : json['my_travels'],
        'thingsILike': !exists(json, 'things_i_like') ? undefined : json['things_i_like'],
        'aboutPlace': !exists(json, 'about_place') ? undefined : json['about_place'],
        'additionalInformation': !exists(json, 'additional_information') ? undefined : json['additional_information'],
        'maxGuests': !exists(json, 'max_guests') ? undefined : json['max_guests'],
        'lastMinute': !exists(json, 'last_minute') ? undefined : json['last_minute'],
        'hasPets': !exists(json, 'has_pets') ? undefined : json['has_pets'],
        'acceptsPets': !exists(json, 'accepts_pets') ? undefined : json['accepts_pets'],
        'petDetails': !exists(json, 'pet_details') ? undefined : json['pet_details'],
        'hasKids': !exists(json, 'has_kids') ? undefined : json['has_kids'],
        'acceptsKids': !exists(json, 'accepts_kids') ? undefined : json['accepts_kids'],
        'kidDetails': !exists(json, 'kid_details') ? undefined : json['kid_details'],
        'hasHousemates': !exists(json, 'has_housemates') ? undefined : json['has_housemates'],
        'housemateDetails': !exists(json, 'housemate_details') ? undefined : json['housemate_details'],
        'wheelchairAccessible': !exists(json, 'wheelchair_accessible') ? undefined : json['wheelchair_accessible'],
        'smokingAllowed': !exists(json, 'smoking_allowed') ? undefined : PatchedUserDetailSmokingAllowedFromJSON(json['smoking_allowed']),
        'smokesAtHome': !exists(json, 'smokes_at_home') ? undefined : json['smokes_at_home'],
        'drinkingAllowed': !exists(json, 'drinking_allowed') ? undefined : json['drinking_allowed'],
        'drinksAtHome': !exists(json, 'drinks_at_home') ? undefined : json['drinks_at_home'],
        'otherHostInfo': !exists(json, 'other_host_info') ? undefined : json['other_host_info'],
        'sleepingArrangement': !exists(json, 'sleeping_arrangement') ? undefined : PatchedUserDetailSleepingArrangementFromJSON(json['sleeping_arrangement']),
        'sleepingDetails': !exists(json, 'sleeping_details') ? undefined : json['sleeping_details'],
        'area': !exists(json, 'area') ? undefined : json['area'],
        'houseRules': !exists(json, 'house_rules') ? undefined : json['house_rules'],
        'parking': !exists(json, 'parking') ? undefined : json['parking'],
        'parkingDetails': !exists(json, 'parking_details') ? undefined : PatchedUserDetailParkingDetailsFromJSON(json['parking_details']),
        'campingOk': !exists(json, 'camping_ok') ? undefined : json['camping_ok'],
        'acceptedTos': !exists(json, 'accepted_tos') ? undefined : json['accepted_tos'],
        'acceptedCommunityGuidelines': !exists(json, 'accepted_community_guidelines') ? undefined : json['accepted_community_guidelines'],
        'filledContributorForm': !exists(json, 'filled_contributor_form') ? undefined : json['filled_contributor_form'],
        'onboardingEmailsSent': !exists(json, 'onboarding_emails_sent') ? undefined : json['onboarding_emails_sent'],
        'lastOnboardingEmailSentAt': !exists(json, 'last_onboarding_email_sent_at') ? undefined : (json['last_onboarding_email_sent_at'] === null ? null : new Date(json['last_onboarding_email_sent_at'])),
        'addedToMailingList': !exists(json, 'added_to_mailing_list') ? undefined : json['added_to_mailing_list'],
        'lastDigestSentAt': !exists(json, 'last_digest_sent_at') ? undefined : (json['last_digest_sent_at'] === null ? null : new Date(json['last_digest_sent_at'])),
        'stripeCustomerId': !exists(json, 'stripe_customer_id') ? undefined : json['stripe_customer_id'],
        'stripeCustomerIdOld': !exists(json, 'stripe_customer_id_old') ? undefined : json['stripe_customer_id_old'],
        'newNotificationsEnabled': !exists(json, 'new_notifications_enabled') ? undefined : json['new_notifications_enabled'],
        'avatarUrl': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
        'timezoneArea': !exists(json, 'timezone_area') ? undefined : json['timezone_area'],
        'age': !exists(json, 'age') ? undefined : json['age'],
        'languageAbilities': !exists(json, 'language_abilities') ? undefined : json['language_abilities'],
        'regionsVisited': !exists(json, 'regions_visited') ? undefined : json['regions_visited'],
        'regionsLived': !exists(json, 'regions_lived') ? undefined : json['regions_lived'],
        'numberOfReferences': !exists(json, 'number_of_references') ? undefined : json['number_of_references'],
        'numberOfFriends': !exists(json, 'number_of_friends') ? undefined : json['number_of_friends'],
    };
}

export function PatchedUserDetailToJSON(value?: PatchedUserDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
        'phone': value.phone,
        'geom': value.geom,
        'geom_radius': value.geomRadius,
        'city': value.city,
        'hometown': value.hometown,
        'last_notified_message_id': value.lastNotifiedMessageId,
        'last_notified_request_message_id': value.lastNotifiedRequestMessageId,
        'name': value.name,
        'gender': value.gender,
        'pronouns': value.pronouns,
        'birthdate': value.birthdate === undefined ? undefined : (value.birthdate === null ? null : value.birthdate.toISOString().substr(0,10)),
        'full_name': value.fullName,
        'hosting_status': HostingStatusEnumToJSON(value.hostingStatus),
        'meetup_status': MeetupStatusEnumToJSON(value.meetupStatus),
        'community_standing': value.communityStanding,
        'occupation': value.occupation,
        'education': value.education,
        'about_me': value.aboutMe,
        'my_travels': value.myTravels,
        'things_i_like': value.thingsILike,
        'about_place': value.aboutPlace,
        'additional_information': value.additionalInformation,
        'max_guests': value.maxGuests,
        'last_minute': value.lastMinute,
        'has_pets': value.hasPets,
        'accepts_pets': value.acceptsPets,
        'pet_details': value.petDetails,
        'has_kids': value.hasKids,
        'accepts_kids': value.acceptsKids,
        'kid_details': value.kidDetails,
        'has_housemates': value.hasHousemates,
        'housemate_details': value.housemateDetails,
        'wheelchair_accessible': value.wheelchairAccessible,
        'smoking_allowed': PatchedUserDetailSmokingAllowedToJSON(value.smokingAllowed),
        'smokes_at_home': value.smokesAtHome,
        'drinking_allowed': value.drinkingAllowed,
        'drinks_at_home': value.drinksAtHome,
        'other_host_info': value.otherHostInfo,
        'sleeping_arrangement': PatchedUserDetailSleepingArrangementToJSON(value.sleepingArrangement),
        'sleeping_details': value.sleepingDetails,
        'area': value.area,
        'house_rules': value.houseRules,
        'parking': value.parking,
        'parking_details': PatchedUserDetailParkingDetailsToJSON(value.parkingDetails),
        'camping_ok': value.campingOk,
        'accepted_tos': value.acceptedTos,
        'accepted_community_guidelines': value.acceptedCommunityGuidelines,
        'filled_contributor_form': value.filledContributorForm,
        'onboarding_emails_sent': value.onboardingEmailsSent,
        'added_to_mailing_list': value.addedToMailingList,
        'last_digest_sent_at': value.lastDigestSentAt === undefined ? undefined : (value.lastDigestSentAt === null ? null : value.lastDigestSentAt.toISOString()),
        'new_notifications_enabled': value.newNotificationsEnabled,
    };
}

