/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedNotificationPreference
 */
export interface PatchedNotificationPreference {
    /**
     * 
     * @type {number}
     * @memberof PatchedNotificationPreference
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedNotificationPreference
     */
    readonly user?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedNotificationPreference
     */
    topicAction?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedNotificationPreference
     */
    deliveryType?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedNotificationPreference
     */
    deliver?: boolean;
}

export function PatchedNotificationPreferenceFromJSON(json: any): PatchedNotificationPreference {
    return PatchedNotificationPreferenceFromJSONTyped(json, false);
}

export function PatchedNotificationPreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedNotificationPreference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'topicAction': !exists(json, 'topic_action') ? undefined : json['topic_action'],
        'deliveryType': !exists(json, 'delivery_type') ? undefined : json['delivery_type'],
        'deliver': !exists(json, 'deliver') ? undefined : json['deliver'],
    };
}

export function PatchedNotificationPreferenceToJSON(value?: PatchedNotificationPreference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic_action': value.topicAction,
        'delivery_type': value.deliveryType,
        'deliver': value.deliver,
    };
}

