/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUpload
 */
export interface PatchedUpload {
    /**
     * 
     * @type {string}
     * @memberof PatchedUpload
     */
    readonly key?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUpload
     */
    readonly filename?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUpload
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedUpload
     */
    readonly credit?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUpload
     */
    readonly user?: number;
}

export function PatchedUploadFromJSON(json: any): PatchedUpload {
    return PatchedUploadFromJSONTyped(json, false);
}

export function PatchedUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUpload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'credit': !exists(json, 'credit') ? undefined : json['credit'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function PatchedUploadToJSON(value?: PatchedUpload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

