/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedComment
 */
export interface PatchedComment {
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedComment
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedComment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedComment
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    readonly thread?: number;
}

export function PatchedCommentFromJSON(json: any): PatchedComment {
    return PatchedCommentFromJSONTyped(json, false);
}

export function PatchedCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'deletedAt': !exists(json, 'deleted_at') ? undefined : (json['deleted_at'] === null ? null : new Date(json['deleted_at'])),
        'user': !exists(json, 'user') ? undefined : json['user'],
        'thread': !exists(json, 'thread') ? undefined : json['thread'],
    };
}

export function PatchedCommentToJSON(value?: PatchedComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

