/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EventOccurrenceAttendeeStatusEnum,
    EventOccurrenceAttendeeStatusEnumFromJSON,
    EventOccurrenceAttendeeStatusEnumFromJSONTyped,
    EventOccurrenceAttendeeStatusEnumToJSON,
} from './EventOccurrenceAttendeeStatusEnum';

/**
 * 
 * @export
 * @interface PatchedEventOccurrenceAttendee
 */
export interface PatchedEventOccurrenceAttendee {
    /**
     * 
     * @type {number}
     * @memberof PatchedEventOccurrenceAttendee
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEventOccurrenceAttendee
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {EventOccurrenceAttendeeStatusEnum}
     * @memberof PatchedEventOccurrenceAttendee
     */
    status?: EventOccurrenceAttendeeStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedEventOccurrenceAttendee
     */
    readonly occurrence?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedEventOccurrenceAttendee
     */
    readonly user?: number;
}

export function PatchedEventOccurrenceAttendeeFromJSON(json: any): PatchedEventOccurrenceAttendee {
    return PatchedEventOccurrenceAttendeeFromJSONTyped(json, false);
}

export function PatchedEventOccurrenceAttendeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEventOccurrenceAttendee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'status': !exists(json, 'status') ? undefined : EventOccurrenceAttendeeStatusEnumFromJSON(json['status']),
        'occurrence': !exists(json, 'occurrence') ? undefined : json['occurrence'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function PatchedEventOccurrenceAttendeeToJSON(value?: PatchedEventOccurrenceAttendee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': EventOccurrenceAttendeeStatusEnumToJSON(value.status),
    };
}

