/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedOneTimeDonation
 */
export interface PatchedOneTimeDonation {
    /**
     * 
     * @type {number}
     * @memberof PatchedOneTimeDonation
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedOneTimeDonation
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedOneTimeDonation
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedOneTimeDonation
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedOneTimeDonation
     */
    stripeCheckoutSessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedOneTimeDonation
     */
    stripePaymentIntentId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedOneTimeDonation
     */
    paid?: Date | null;
}

export function PatchedOneTimeDonationFromJSON(json: any): PatchedOneTimeDonation {
    return PatchedOneTimeDonationFromJSONTyped(json, false);
}

export function PatchedOneTimeDonationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedOneTimeDonation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'user': !exists(json, 'user') ? undefined : json['user'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'stripeCheckoutSessionId': !exists(json, 'stripe_checkout_session_id') ? undefined : json['stripe_checkout_session_id'],
        'stripePaymentIntentId': !exists(json, 'stripe_payment_intent_id') ? undefined : json['stripe_payment_intent_id'],
        'paid': !exists(json, 'paid') ? undefined : (json['paid'] === null ? null : new Date(json['paid'])),
    };
}

export function PatchedOneTimeDonationToJSON(value?: PatchedOneTimeDonation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'stripe_checkout_session_id': value.stripeCheckoutSessionId,
        'stripe_payment_intent_id': value.stripePaymentIntentId,
        'paid': value.paid === undefined ? undefined : (value.paid === null ? null : value.paid.toISOString()),
    };
}

