/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTimezoneArea
 */
export interface PatchedTimezoneArea {
    /**
     * 
     * @type {number}
     * @memberof PatchedTimezoneArea
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTimezoneArea
     */
    tzid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedTimezoneArea
     */
    geom?: string;
}

export function PatchedTimezoneAreaFromJSON(json: any): PatchedTimezoneArea {
    return PatchedTimezoneAreaFromJSONTyped(json, false);
}

export function PatchedTimezoneAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTimezoneArea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tzid': !exists(json, 'tzid') ? undefined : json['tzid'],
        'geom': !exists(json, 'geom') ? undefined : json['geom'],
    };
}

export function PatchedTimezoneAreaToJSON(value?: PatchedTimezoneArea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tzid': value.tzid,
        'geom': value.geom,
    };
}

