/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import {
    SleepingArrangementEnum,
    SleepingArrangementEnumFromJSON,
    SleepingArrangementEnumFromJSONTyped,
    SleepingArrangementEnumToJSON,
} from './SleepingArrangementEnum';

/**
 * @type PatchedUserDetailSleepingArrangement
 * 
 * @export
 */
export type PatchedUserDetailSleepingArrangement = NullEnum | SleepingArrangementEnum;

export function PatchedUserDetailSleepingArrangementFromJSON(json: any): PatchedUserDetailSleepingArrangement {
    return PatchedUserDetailSleepingArrangementFromJSONTyped(json, false);
}

export function PatchedUserDetailSleepingArrangementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetailSleepingArrangement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...NullEnumFromJSONTyped(json, true), ...SleepingArrangementEnumFromJSONTyped(json, true) };
}

export function PatchedUserDetailSleepingArrangementToJSON(value?: PatchedUserDetailSleepingArrangement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...NullEnumToJSON(value), ...SleepingArrangementEnumToJSON(value) };
}

