/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPageVersion
 */
export interface PatchedPageVersion {
    /**
     * 
     * @type {number}
     * @memberof PatchedPageVersion
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPageVersion
     */
    readonly page?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPageVersion
     */
    readonly user?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedPageVersion
     */
    readonly upload?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPageVersion
     */
    readonly title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPageVersion
     */
    readonly content?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPageVersion
     */
    readonly address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPageVersion
     */
    readonly geom?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedPageVersion
     */
    readonly createdAt?: Date;
}

export function PatchedPageVersionFromJSON(json: any): PatchedPageVersion {
    return PatchedPageVersionFromJSONTyped(json, false);
}

export function PatchedPageVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPageVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'upload': !exists(json, 'upload') ? undefined : json['upload'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'geom': !exists(json, 'geom') ? undefined : json['geom'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedPageVersionToJSON(value?: PatchedPageVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

