/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserBlock
 */
export interface PatchedUserBlock {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserBlock
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserBlock
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserBlock
     */
    blockedUser?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserBlock
     */
    readonly blockedUserName?: string;
}

export function PatchedUserBlockFromJSON(json: any): PatchedUserBlock {
    return PatchedUserBlockFromJSONTyped(json, false);
}

export function PatchedUserBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'blockedUser': !exists(json, 'blocked_user') ? undefined : json['blocked_user'],
        'blockedUserName': !exists(json, 'blocked_user_name') ? undefined : json['blocked_user_name'],
    };
}

export function PatchedUserBlockToJSON(value?: PatchedUserBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blocked_user': value.blockedUser,
    };
}

