/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedDiscussion
 */
export interface PatchedDiscussion {
    /**
     * 
     * @type {number}
     * @memberof PatchedDiscussion
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedDiscussion
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedDiscussion
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDiscussion
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedDiscussion
     */
    readonly thread?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedDiscussion
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedDiscussion
     */
    readonly ownerCluster?: number;
}

export function PatchedDiscussionFromJSON(json: any): PatchedDiscussion {
    return PatchedDiscussionFromJSONTyped(json, false);
}

export function PatchedDiscussionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDiscussion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'thread': !exists(json, 'thread') ? undefined : json['thread'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'ownerCluster': !exists(json, 'owner_cluster') ? undefined : json['owner_cluster'],
    };
}

export function PatchedDiscussionToJSON(value?: PatchedDiscussion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
    };
}

