/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSMSS
 */
export interface PatchedSMSS {
    /**
     * 
     * @type {number}
     * @memberof PatchedSMSS
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSMSS
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedSMSS
     */
    readonly messageId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSMSS
     */
    readonly smsSenderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSMSS
     */
    readonly number?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSMSS
     */
    readonly message?: string;
}

export function PatchedSMSSFromJSON(json: any): PatchedSMSS {
    return PatchedSMSSFromJSONTyped(json, false);
}

export function PatchedSMSSFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSMSS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'messageId': !exists(json, 'message_id') ? undefined : json['message_id'],
        'smsSenderId': !exists(json, 'sms_sender_id') ? undefined : json['sms_sender_id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function PatchedSMSSToJSON(value?: PatchedSMSS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

