/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FriendRelationshipStatusEnum,
    FriendRelationshipStatusEnumFromJSON,
    FriendRelationshipStatusEnumFromJSONTyped,
    FriendRelationshipStatusEnumToJSON,
} from './FriendRelationshipStatusEnum';

/**
 * 
 * @export
 * @interface PatchedFriendRelationship
 */
export interface PatchedFriendRelationship {
    /**
     * 
     * @type {number}
     * @memberof PatchedFriendRelationship
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedFriendRelationship
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedFriendRelationship
     */
    readonly toUser?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFriendRelationship
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFriendRelationship
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {FriendRelationshipStatusEnum}
     * @memberof PatchedFriendRelationship
     */
    status?: FriendRelationshipStatusEnum;
}

export function PatchedFriendRelationshipFromJSON(json: any): PatchedFriendRelationship {
    return PatchedFriendRelationshipFromJSONTyped(json, false);
}

export function PatchedFriendRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFriendRelationship {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'toUser': !exists(json, 'to_user') ? undefined : json['to_user'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (json['updated_at'] === null ? null : new Date(json['updated_at'])),
        'status': !exists(json, 'status') ? undefined : FriendRelationshipStatusEnumFromJSON(json['status']),
    };
}

export function PatchedFriendRelationshipToJSON(value?: PatchedFriendRelationship | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt === null ? null : value.updatedAt.toISOString()),
        'status': FriendRelationshipStatusEnumToJSON(value.status),
    };
}

