/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContributorFormContribute,
    ContributorFormContributeFromJSON,
    ContributorFormContributeFromJSONTyped,
    ContributorFormContributeToJSON,
} from './ContributorFormContribute';

/**
 * 
 * @export
 * @interface PatchedContributorForm
 */
export interface PatchedContributorForm {
    /**
     * 
     * @type {number}
     * @memberof PatchedContributorForm
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedContributorForm
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedContributorForm
     */
    readonly ideas?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedContributorForm
     */
    readonly features?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedContributorForm
     */
    readonly experience?: string | null;
    /**
     * 
     * @type {ContributorFormContribute}
     * @memberof PatchedContributorForm
     */
    contribute?: ContributorFormContribute | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedContributorForm
     */
    contributeWays?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedContributorForm
     */
    expertise?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedContributorForm
     */
    readonly user?: number;
}

export function PatchedContributorFormFromJSON(json: any): PatchedContributorForm {
    return PatchedContributorFormFromJSONTyped(json, false);
}

export function PatchedContributorFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedContributorForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'ideas': !exists(json, 'ideas') ? undefined : json['ideas'],
        'features': !exists(json, 'features') ? undefined : json['features'],
        'experience': !exists(json, 'experience') ? undefined : json['experience'],
        'contribute': !exists(json, 'contribute') ? undefined : ContributorFormContributeFromJSON(json['contribute']),
        'contributeWays': !exists(json, 'contribute_ways') ? undefined : json['contribute_ways'],
        'expertise': !exists(json, 'expertise') ? undefined : json['expertise'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function PatchedContributorFormToJSON(value?: PatchedContributorForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contribute': ContributorFormContributeToJSON(value.contribute),
        'contribute_ways': value.contributeWays,
        'expertise': value.expertise,
    };
}

