/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Status34bEnum,
    Status34bEnumFromJSON,
    Status34bEnumFromJSONTyped,
    Status34bEnumToJSON,
} from './Status34bEnum';

/**
 * 
 * @export
 * @interface PatchedHostRequest
 */
export interface PatchedHostRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    readonly conversation?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    readonly hostUser?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHostRequest
     */
    startAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHostRequest
     */
    endAt?: Date;
    /**
     * 
     * @type {Status34bEnum}
     * @memberof PatchedHostRequest
     */
    status?: Status34bEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    userLastSeenMessageId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    hostLastSeenMessageId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    userSentReferenceReminders?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedHostRequest
     */
    hostSentReferenceReminders?: number;
}

export function PatchedHostRequestFromJSON(json: any): PatchedHostRequest {
    return PatchedHostRequestFromJSONTyped(json, false);
}

export function PatchedHostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedHostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'conversation': !exists(json, 'conversation') ? undefined : json['conversation'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'hostUser': !exists(json, 'host_user') ? undefined : json['host_user'],
        'startAt': !exists(json, 'start_at') ? undefined : (new Date(json['start_at'])),
        'endAt': !exists(json, 'end_at') ? undefined : (new Date(json['end_at'])),
        'status': !exists(json, 'status') ? undefined : Status34bEnumFromJSON(json['status']),
        'userLastSeenMessageId': !exists(json, 'user_last_seen_message_id') ? undefined : json['user_last_seen_message_id'],
        'hostLastSeenMessageId': !exists(json, 'host_last_seen_message_id') ? undefined : json['host_last_seen_message_id'],
        'userSentReferenceReminders': !exists(json, 'user_sent_reference_reminders') ? undefined : json['user_sent_reference_reminders'],
        'hostSentReferenceReminders': !exists(json, 'host_sent_reference_reminders') ? undefined : json['host_sent_reference_reminders'],
    };
}

export function PatchedHostRequestToJSON(value?: PatchedHostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_at': value.startAt === undefined ? undefined : (value.startAt.toISOString()),
        'end_at': value.endAt === undefined ? undefined : (value.endAt.toISOString()),
        'status': Status34bEnumToJSON(value.status),
        'user_last_seen_message_id': value.userLastSeenMessageId,
        'host_last_seen_message_id': value.hostLastSeenMessageId,
        'user_sent_reference_reminders': value.userSentReferenceReminders,
        'host_sent_reference_reminders': value.hostSentReferenceReminders,
    };
}

