/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedThread
 */
export interface PatchedThread {
    /**
     * 
     * @type {number}
     * @memberof PatchedThread
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedThread
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedThread
     */
    readonly deletedAt?: Date;
}

export function PatchedThreadFromJSON(json: any): PatchedThread {
    return PatchedThreadFromJSONTyped(json, false);
}

export function PatchedThreadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedThread {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'deletedAt': !exists(json, 'deleted_at') ? undefined : (new Date(json['deleted_at'])),
    };
}

export function PatchedThreadToJSON(value?: PatchedThread | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

