/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HostingStatusEnum,
    HostingStatusEnumFromJSON,
    HostingStatusEnumFromJSONTyped,
    HostingStatusEnumToJSON,
} from './HostingStatusEnum';
import {
    MeetupStatusEnum,
    MeetupStatusEnumFromJSON,
    MeetupStatusEnumFromJSONTyped,
    MeetupStatusEnumToJSON,
} from './MeetupStatusEnum';
import {
    PatchedUserParkingDetails,
    PatchedUserParkingDetailsFromJSON,
    PatchedUserParkingDetailsFromJSONTyped,
    PatchedUserParkingDetailsToJSON,
} from './PatchedUserParkingDetails';
import {
    PatchedUserSleepingArrangement,
    PatchedUserSleepingArrangementFromJSON,
    PatchedUserSleepingArrangementFromJSONTyped,
    PatchedUserSleepingArrangementToJSON,
} from './PatchedUserSleepingArrangement';
import {
    PatchedUserSmokingAllowed,
    PatchedUserSmokingAllowedFromJSON,
    PatchedUserSmokingAllowedFromJSONTyped,
    PatchedUserSmokingAllowedToJSON,
} from './PatchedUserSmokingAllowed';

/**
 * 
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly hometown?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly pronouns?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    readonly birthdate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly fullName?: string | null;
    /**
     * 
     * @type {HostingStatusEnum}
     * @memberof PatchedUser
     */
    readonly hostingStatus?: HostingStatusEnum | null;
    /**
     * 
     * @type {MeetupStatusEnum}
     * @memberof PatchedUser
     */
    readonly meetupStatus?: MeetupStatusEnum | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    readonly communityStanding?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly education?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly aboutMe?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly myTravels?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly thingsILike?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly aboutPlace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly additionalInformation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    readonly maxGuests?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly lastMinute?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly hasPets?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly acceptsPets?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly petDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly hasKids?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly acceptsKids?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly kidDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly hasHousemates?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly housemateDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly wheelchairAccessible?: boolean | null;
    /**
     * 
     * @type {PatchedUserSmokingAllowed}
     * @memberof PatchedUser
     */
    smokingAllowed?: PatchedUserSmokingAllowed | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly smokesAtHome?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly drinkingAllowed?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly drinksAtHome?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly otherHostInfo?: string | null;
    /**
     * 
     * @type {PatchedUserSleepingArrangement}
     * @memberof PatchedUser
     */
    sleepingArrangement?: PatchedUserSleepingArrangement | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly sleepingDetails?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly area?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly houseRules?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly parking?: boolean | null;
    /**
     * 
     * @type {PatchedUserParkingDetails}
     * @memberof PatchedUser
     */
    parkingDetails?: PatchedUserParkingDetails | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly campingOk?: boolean | null;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
    return PatchedUserFromJSONTyped(json, false);
}

export function PatchedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'hometown': !exists(json, 'hometown') ? undefined : json['hometown'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'pronouns': !exists(json, 'pronouns') ? undefined : json['pronouns'],
        'birthdate': !exists(json, 'birthdate') ? undefined : (json['birthdate'] === null ? null : new Date(json['birthdate'])),
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'hostingStatus': !exists(json, 'hosting_status') ? undefined : HostingStatusEnumFromJSON(json['hosting_status']),
        'meetupStatus': !exists(json, 'meetup_status') ? undefined : MeetupStatusEnumFromJSON(json['meetup_status']),
        'communityStanding': !exists(json, 'community_standing') ? undefined : json['community_standing'],
        'occupation': !exists(json, 'occupation') ? undefined : json['occupation'],
        'education': !exists(json, 'education') ? undefined : json['education'],
        'aboutMe': !exists(json, 'about_me') ? undefined : json['about_me'],
        'myTravels': !exists(json, 'my_travels') ? undefined : json['my_travels'],
        'thingsILike': !exists(json, 'things_i_like') ? undefined : json['things_i_like'],
        'aboutPlace': !exists(json, 'about_place') ? undefined : json['about_place'],
        'additionalInformation': !exists(json, 'additional_information') ? undefined : json['additional_information'],
        'maxGuests': !exists(json, 'max_guests') ? undefined : json['max_guests'],
        'lastMinute': !exists(json, 'last_minute') ? undefined : json['last_minute'],
        'hasPets': !exists(json, 'has_pets') ? undefined : json['has_pets'],
        'acceptsPets': !exists(json, 'accepts_pets') ? undefined : json['accepts_pets'],
        'petDetails': !exists(json, 'pet_details') ? undefined : json['pet_details'],
        'hasKids': !exists(json, 'has_kids') ? undefined : json['has_kids'],
        'acceptsKids': !exists(json, 'accepts_kids') ? undefined : json['accepts_kids'],
        'kidDetails': !exists(json, 'kid_details') ? undefined : json['kid_details'],
        'hasHousemates': !exists(json, 'has_housemates') ? undefined : json['has_housemates'],
        'housemateDetails': !exists(json, 'housemate_details') ? undefined : json['housemate_details'],
        'wheelchairAccessible': !exists(json, 'wheelchair_accessible') ? undefined : json['wheelchair_accessible'],
        'smokingAllowed': !exists(json, 'smoking_allowed') ? undefined : PatchedUserSmokingAllowedFromJSON(json['smoking_allowed']),
        'smokesAtHome': !exists(json, 'smokes_at_home') ? undefined : json['smokes_at_home'],
        'drinkingAllowed': !exists(json, 'drinking_allowed') ? undefined : json['drinking_allowed'],
        'drinksAtHome': !exists(json, 'drinks_at_home') ? undefined : json['drinks_at_home'],
        'otherHostInfo': !exists(json, 'other_host_info') ? undefined : json['other_host_info'],
        'sleepingArrangement': !exists(json, 'sleeping_arrangement') ? undefined : PatchedUserSleepingArrangementFromJSON(json['sleeping_arrangement']),
        'sleepingDetails': !exists(json, 'sleeping_details') ? undefined : json['sleeping_details'],
        'area': !exists(json, 'area') ? undefined : json['area'],
        'houseRules': !exists(json, 'house_rules') ? undefined : json['house_rules'],
        'parking': !exists(json, 'parking') ? undefined : json['parking'],
        'parkingDetails': !exists(json, 'parking_details') ? undefined : PatchedUserParkingDetailsFromJSON(json['parking_details']),
        'campingOk': !exists(json, 'camping_ok') ? undefined : json['camping_ok'],
    };
}

export function PatchedUserToJSON(value?: PatchedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'smoking_allowed': PatchedUserSmokingAllowedToJSON(value.smokingAllowed),
        'sleeping_arrangement': PatchedUserSleepingArrangementToJSON(value.sleepingArrangement),
        'parking_details': PatchedUserParkingDetailsToJSON(value.parkingDetails),
    };
}

