/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MessageHostRequestStatusTarget,
    MessageHostRequestStatusTargetFromJSON,
    MessageHostRequestStatusTargetFromJSONTyped,
    MessageHostRequestStatusTargetToJSON,
} from './MessageHostRequestStatusTarget';
import {
    MessageMessageType,
    MessageMessageTypeFromJSON,
    MessageMessageTypeFromJSONTyped,
    MessageMessageTypeToJSON,
} from './MessageMessageType';

/**
 * 
 * @export
 * @interface PatchedMessage
 */
export interface PatchedMessage {
    /**
     * 
     * @type {number}
     * @memberof PatchedMessage
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedMessage
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedMessage
     */
    readonly toUser?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedMessage
     */
    readonly conversation?: number;
    /**
     * 
     * @type {MessageMessageType}
     * @memberof PatchedMessage
     */
    messageType?: MessageMessageType | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedMessage
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedMessage
     */
    readonly text?: string | null;
    /**
     * 
     * @type {MessageHostRequestStatusTarget}
     * @memberof PatchedMessage
     */
    hostRequestStatusTarget?: MessageHostRequestStatusTarget | null;
}

export function PatchedMessageFromJSON(json: any): PatchedMessage {
    return PatchedMessageFromJSONTyped(json, false);
}

export function PatchedMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'toUser': !exists(json, 'to_user') ? undefined : json['to_user'],
        'conversation': !exists(json, 'conversation') ? undefined : json['conversation'],
        'messageType': !exists(json, 'message_type') ? undefined : MessageMessageTypeFromJSON(json['message_type']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'text': !exists(json, 'text') ? undefined : json['text'],
        'hostRequestStatusTarget': !exists(json, 'host_request_status_target') ? undefined : MessageHostRequestStatusTargetFromJSON(json['host_request_status_target']),
    };
}

export function PatchedMessageToJSON(value?: PatchedMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message_type': MessageMessageTypeToJSON(value.messageType),
        'host_request_status_target': MessageHostRequestStatusTargetToJSON(value.hostRequestStatusTarget),
    };
}

