/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedContentReport
 */
export interface PatchedContentReport {
    /**
     * 
     * @type {number}
     * @memberof PatchedContentReport
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedContentReport
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedContentReport
     */
    readonly reason?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedContentReport
     */
    readonly description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedContentReport
     */
    readonly contentRef?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedContentReport
     */
    readonly userAgent?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedContentReport
     */
    readonly page?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedContentReport
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedContentReport
     */
    readonly filedByUser?: number;
}

export function PatchedContentReportFromJSON(json: any): PatchedContentReport {
    return PatchedContentReportFromJSONTyped(json, false);
}

export function PatchedContentReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedContentReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'contentRef': !exists(json, 'content_ref') ? undefined : json['content_ref'],
        'userAgent': !exists(json, 'user_agent') ? undefined : json['user_agent'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'filedByUser': !exists(json, 'filed_by_user') ? undefined : json['filed_by_user'],
    };
}

export function PatchedContentReportToJSON(value?: PatchedContentReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

