/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleEnum,
    RoleEnumFromJSON,
    RoleEnumFromJSONTyped,
    RoleEnumToJSON,
} from './RoleEnum';

/**
 * 
 * @export
 * @interface PatchedClusterSubscription
 */
export interface PatchedClusterSubscription {
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterSubscription
     */
    readonly id?: number;
    /**
     * 
     * @type {RoleEnum}
     * @memberof PatchedClusterSubscription
     */
    role?: RoleEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterSubscription
     */
    readonly user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterSubscription
     */
    cluster?: number;
}

export function PatchedClusterSubscriptionFromJSON(json: any): PatchedClusterSubscription {
    return PatchedClusterSubscriptionFromJSONTyped(json, false);
}

export function PatchedClusterSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedClusterSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'role': !exists(json, 'role') ? undefined : RoleEnumFromJSON(json['role']),
        'user': !exists(json, 'user') ? undefined : json['user'],
        'cluster': !exists(json, 'cluster') ? undefined : json['cluster'],
    };
}

export function PatchedClusterSubscriptionToJSON(value?: PatchedClusterSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': RoleEnumToJSON(value.role),
        'cluster': value.cluster,
    };
}

