/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedRegion
 */
export interface PatchedRegion {
    /**
     * 
     * @type {number}
     * @memberof PatchedRegion
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedRegion
     */
    readonly code?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRegion
     */
    name?: string;
}

export function PatchedRegionFromJSON(json: any): PatchedRegion {
    return PatchedRegionFromJSONTyped(json, false);
}

export function PatchedRegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRegion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedRegionToJSON(value?: PatchedRegion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

