/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringDonation
 */
export interface RecurringDonation {
    /**
     * 
     * @type {number}
     * @memberof RecurringDonation
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof RecurringDonation
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof RecurringDonation
     */
    readonly user: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringDonation
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringDonation
     */
    stripeCheckoutSessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecurringDonation
     */
    stripeSubscriptionId?: string | null;
}

export function RecurringDonationFromJSON(json: any): RecurringDonation {
    return RecurringDonationFromJSONTyped(json, false);
}

export function RecurringDonationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringDonation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'user': json['user'],
        'amount': json['amount'],
        'stripeCheckoutSessionId': !exists(json, 'stripe_checkout_session_id') ? undefined : json['stripe_checkout_session_id'],
        'stripeSubscriptionId': !exists(json, 'stripe_subscription_id') ? undefined : json['stripe_subscription_id'],
    };
}

export function RecurringDonationToJSON(value?: RecurringDonation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'stripe_checkout_session_id': value.stripeCheckoutSessionId,
        'stripe_subscription_id': value.stripeSubscriptionId,
    };
}

