/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReferenceTypeEnum,
    ReferenceTypeEnumFromJSON,
    ReferenceTypeEnumFromJSONTyped,
    ReferenceTypeEnumToJSON,
} from './ReferenceTypeEnum';

/**
 * 
 * @export
 * @interface Reference
 */
export interface Reference {
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Reference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    readonly user: number;
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    readonly aboutUser: number;
    /**
     * 
     * @type {ReferenceTypeEnum}
     * @memberof Reference
     */
    readonly type: ReferenceTypeEnum | null;
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    readonly hostRequest: number | null;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof Reference
     */
    rating: number;
    /**
     * 
     * @type {boolean}
     * @memberof Reference
     */
    wasAppropriate: boolean;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    privateText?: string | null;
}

export function ReferenceFromJSON(json: any): Reference {
    return ReferenceFromJSONTyped(json, false);
}

export function ReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'user': json['user'],
        'aboutUser': json['about_user'],
        'type': ReferenceTypeEnumFromJSON(json['type']),
        'hostRequest': json['host_request'],
        'text': json['text'],
        'rating': json['rating'],
        'wasAppropriate': json['was_appropriate'],
        'privateText': !exists(json, 'private_text') ? undefined : json['private_text'],
    };
}

export function ReferenceToJSON(value?: Reference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'rating': value.rating,
        'was_appropriate': value.wasAppropriate,
        'private_text': value.privateText,
    };
}

