/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReferenceTypeEnum = {
    Friend: 'friend',
    Surfed: 'surfed',
    Hosted: 'hosted'
} as const;
export type ReferenceTypeEnum = typeof ReferenceTypeEnum[keyof typeof ReferenceTypeEnum];


export function ReferenceTypeEnumFromJSON(json: any): ReferenceTypeEnum {
    return ReferenceTypeEnumFromJSONTyped(json, false);
}

export function ReferenceTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceTypeEnum {
    return json as ReferenceTypeEnum;
}

export function ReferenceTypeEnumToJSON(value?: ReferenceTypeEnum | null): any {
    return value as any;
}

