/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SMSS
 */
export interface SMSS {
    /**
     * 
     * @type {number}
     * @memberof SMSS
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof SMSS
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SMSS
     */
    readonly messageId: string;
    /**
     * 
     * @type {string}
     * @memberof SMSS
     */
    readonly smsSenderId: string;
    /**
     * 
     * @type {string}
     * @memberof SMSS
     */
    readonly number: string;
    /**
     * 
     * @type {string}
     * @memberof SMSS
     */
    readonly message: string;
}

export function SMSSFromJSON(json: any): SMSS {
    return SMSSFromJSONTyped(json, false);
}

export function SMSSFromJSONTyped(json: any, ignoreDiscriminator: boolean): SMSS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'messageId': json['message_id'],
        'smsSenderId': json['sms_sender_id'],
        'number': json['number'],
        'message': json['message'],
    };
}

export function SMSSToJSON(value?: SMSS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

