/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimezoneArea
 */
export interface TimezoneArea {
    /**
     * 
     * @type {number}
     * @memberof TimezoneArea
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneArea
     */
    tzid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimezoneArea
     */
    geom: string;
}

export function TimezoneAreaFromJSON(json: any): TimezoneArea {
    return TimezoneAreaFromJSONTyped(json, false);
}

export function TimezoneAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimezoneArea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tzid': !exists(json, 'tzid') ? undefined : json['tzid'],
        'geom': json['geom'],
    };
}

export function TimezoneAreaToJSON(value?: TimezoneArea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tzid': value.tzid,
        'geom': value.geom,
    };
}

