/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Upload
 */
export interface Upload {
    /**
     * 
     * @type {string}
     * @memberof Upload
     */
    readonly key: string;
    /**
     * 
     * @type {string}
     * @memberof Upload
     */
    readonly filename: string;
    /**
     * 
     * @type {Date}
     * @memberof Upload
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Upload
     */
    readonly credit: string | null;
    /**
     * 
     * @type {number}
     * @memberof Upload
     */
    readonly user: number;
}

export function UploadFromJSON(json: any): Upload {
    return UploadFromJSONTyped(json, false);
}

export function UploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Upload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'filename': json['filename'],
        'createdAt': (new Date(json['created_at'])),
        'credit': json['credit'],
        'user': json['user'],
    };
}

export function UploadToJSON(value?: Upload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

