/* tslint:disable */
/* eslint-disable */
/**
 * Couchers API
 * Couchers API documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
} from './NullEnum';
import {
    ParkingDetailsEnum,
    ParkingDetailsEnumFromJSON,
    ParkingDetailsEnumFromJSONTyped,
    ParkingDetailsEnumToJSON,
} from './ParkingDetailsEnum';

/**
 * @type UserDetailParkingDetails
 * 
 * @export
 */
export type UserDetailParkingDetails = NullEnum | ParkingDetailsEnum;

export function UserDetailParkingDetailsFromJSON(json: any): UserDetailParkingDetails {
    return UserDetailParkingDetailsFromJSONTyped(json, false);
}

export function UserDetailParkingDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailParkingDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...NullEnumFromJSONTyped(json, true), ...ParkingDetailsEnumFromJSONTyped(json, true) };
}

export function UserDetailParkingDetailsToJSON(value?: UserDetailParkingDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...NullEnumToJSON(value), ...ParkingDetailsEnumToJSON(value) };
}

