name: Frontend CI

on:
  push:
    branches-ignore:
      - master
      - master-hotfix

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [self-hosted, master]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-push-ecr
        with:
          module-name: frontend
          src-path: ./


  test-web:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-protos
      - run: |
          yarn install
          yarn test-ci

  test-web-prettier:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-protos
      - run: |
          yarn install
          yarn prettier --check *

  test-storybook:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-protos
      - run: |
          yarn install
          yarn build-storybook


  deploy-dev:
    runs-on: [self-hosted, master]
    needs: [test-web, test-web-prettier, test-storybook]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/helm-deploy
        with:
          module-name: frontend
          environment-slug: dev
          environment-name: ${{ env.ENV_NAME }}
          environment-url: ${{ env.ENV_URL }}
