name: Prod - Deploy Frontend on Release

on:
  workflow_call:
  # release:
  #   types: [published]

defaults:
  run:
    shell: bash

jobs:

  build-prod:
    runs-on: [self-hosted, master]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-push-ecr
        with:
          module-name: frontend
          build-for-environment: production

  deploy-prod:
    runs-on: [self-hosted, master]
    needs: build-prod
    environment:
      name: prod
      url: couchers.org
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/helm-deploy
        with:
          environment-slug: prod
          environment-name: prod
          image-tag: production-${{ env.SLUG }}

  notify-slack:
    runs-on: [self-hosted, master]
    needs: deploy-prod
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
           # C03GZ5JKHP1 = Channel #deployment-notifications
          payload: |
            {
              "username": "Github Actions - Deploy Notification",
              "icon_url": "https://avatars.githubusercontent.com/u/44036562?s=280&v=4",
              "text": "${{ github.repository }} was Deployed to Production",
              "channel": "C03GZ5JKHP1",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "We have just deployed <https://github.com/${{ github.repository }}|${{ github.repository }}> to <https://couchers.org|Production>.\n*User*: <https://github.com/${{ github.actor }}|${{ github.actor }}>\n*Ref:* <https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}|${{ github.ref_name }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
