name: Staging - Deploy Frontend on Merge

on:
  pull_request:
    types: [closed]
    branches: [master]

defaults:
  run:
    shell: bash

jobs:

  deploy-staging:
    runs-on: [self-hosted, master]
    environment:
      name: staging
      url: next.couchershq.org
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/helm-deploy
        with:
          environment-slug: staging
          environment-name: staging
